### ISSUE TITLE
Make CTA more evident

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#225] opened 2018-02-13 15:44 UTC
Where do I have to click ?

<img width="1296" alt="capture d ecran 2018-02-13 a 16 42 48" src="https://user-images.githubusercontent.com/329236/36158793-75db9bea-10dd-11e8-9dd6-0a5f54ea4b00.png">

**Comment by Tristramg** [comment] 2018-05-23 16:54
duplicate of #226

**Closed by Tristramg** 2018-05-23 16:54 UTC
Labels: work:improvement
